USE UniWorks;

INSERT INTO users (email, password, user_type, full_name) VALUES
    ('keithsmith@example.com', '7tfOO(p**r', 'Admin', 'Samuel Wood'),
    ('lbenson@example.org', '2gx9HxTyq!', 'Admin', 'Lisa Lee'),
    ('ashley39@example.org', '&7I6wnnv_m', 'Admin', 'Savannah Ford'),
    ('thomas48@example.com', '6d1FoSRkx%', 'Admin', 'Lindsay Burns'),
    ('seanhernandez@example.org', '@6AecZrB20', 'Admin', 'Dana Ramsey'),
    ('arroyohunter@example.com', 'E0UZf0rY_s', 'Job Poster', 'Nathan Franklin'),
    ('rachel61@example.com', 'rYF9EPxb+%', 'Job Poster', 'Dr. Terri Anderson'),
    ('obest@example.org', '%yDp8oWpu7', 'Student', 'Brittany Ortiz'),
    ('hoffmanjoseph@example.com', 'z2P23tCe^R', 'Student', 'Jennifer Mejia'),
    ('collin51@example.org', 's+p4Oe)fAu', 'Admin', 'Jennifer Mullen'),
    ('gharris@example.org', ')a88O(Jl!Y', 'Job Poster', 'Aaron Robinson'),
    ('crystalhamilton@example.net', 'GWR1bF(p!z', 'Student', 'Jillian Green'),
    ('hannajerry@example.net', '%P7PFDTdC^', 'Admin', 'Jeremy Green'),
    ('johnwallace@example.com', '1aR3e6jq*2', 'Job Poster', 'Jennifer Butler'),
    ('hamptonhannah@example.com', '!6xoQdaJ2Q', 'Job Poster', 'Kathy Haynes'),
    ('nathanwood@example.net', '#mzW)*Wq%6', 'Admin', 'Mrs. Kayla Martin MD'),
    ('imartin@example.net', 'iG9_4Jdn&5', 'Job Poster', 'Gary Gutierrez'),
    ('andrea43@example.org', '$*0A!Knz_O', 'Admin', 'Amanda Martin'),
    ('scottjoseph@example.org', '!TRtDGqFz0', 'Job Poster', 'Robert Donaldson'),
    ('scott08@example.net', 'Q8FpQIif#8', 'Admin', 'Jamie Vega'),
    ('eramsey@example.org', '4FGAnMYo)Z', 'Job Poster', 'Debra Graves'),
    ('sarah24@example.com', '$10@SHbFvk', 'Student', 'Mike Norris'),
    ('uwhite@example.com', '(2O5p7Sh73', 'Job Poster', 'Heather Drake'),
    ('skennedy@example.net', 't$M2vWRzwB', 'Job Poster', 'Daniel Mcclure'),
    ('nraymond@example.com', 'J!82QoVK$p', 'Student', 'Diane Torres'),
    ('jason22@example.org', '#V)35GYcw+', 'Admin', 'Rick Bowen'),
    ('laura64@example.org', 'N3E_Fz#q@p', 'Job Poster', 'Tyler Smith'),
    ('andrewstewart@example.com', 'E1_i1W+t@(', 'Admin', 'Joanna Ryan'),
    ('cindy51@example.com', '+R9Qodl9mf', 'Student', 'Michael Nelson'),
    ('lauren46@example.com', '%^0JO%cnQl', 'Job Poster', 'Harold Thomas');

INSERT INTO admins (role, user_id) VALUES
    ('Backend Engineer', 9),
    ('College Administrator', 4),
    ('Frontend Engineer', 27),
    ('College Administrator', 28),
    ('College Administrator', 7),
    ('Frontend Engineer', 16),
    ('Frontend Engineer', 6),
    ('Frontend Engineer', 24),
    ('IT Employee', 2),
    ('IT Employee', 17),
    ('College Administrator', 24),
    ('College Administrator', 25),
    ('Backend Engineer', 13),
    ('College Administrator', 29),
    ('Frontend Engineer', 11),
    ('College Administrator', 15),
    ('Frontend Engineer', 28),
    ('IT Employee', 26),
    ('College Administrator', 27),
    ('Frontend Engineer', 30),
    ('College Administrator', 4),
    ('College Administrator', 19),
    ('College Administrator', 4),
    ('College Administrator', 18),
    ('College Administrator', 25),
    ('Backend Engineer', 30),
    ('Backend Engineer', 3),
    ('Frontend Engineer', 16),
    ('Backend Engineer', 8),
    ('Backend Engineer', 21);

INSERT INTO job_seekers (major, university, profile_picture, city_state, phone_number, degree_level, graduation_year, user_id) VALUES
    ('Electrical Engineering', 'Gray University', 'https://placekittens.com/532/676', 'Jasonfurt/IN', '217.382.7156', 'Masters', '2027-08-14', 26),
    ('Computer Engineering', 'Fischer University', 'https://placekittens.com/172/296', 'Kentborough/AZ', '571-927-7676x4620', 'Masters', '2026-03-06', 27),
    ('Data Science', 'Roberts University', 'https://placekittens.com/817/173', 'New Christinafort/DC', '001-813-227-0944', 'PHD', '2030-01-09', 14),
    ('French Literature', 'Flores University', 'https://dummyimage.com/191x84', 'Williamschester/IN', '+1-778-246-3122x691', 'PHD', '2027-12-04', 7),
    ('Mechanical Engineering', 'Barnett University', 'https://picsum.photos/934/971', 'Laurabury/AS', '001-635-548-4008x1335', 'Masters', '2028-05-28', 3),
    ('Computer Engineering', 'Schmidt University', 'https://picsum.photos/355/353', 'East Sarahville/RI', '001-536-293-0415x402', 'Masters', '2028-04-01', 5),
    ('Mathematics', 'Abbott University', 'https://picsum.photos/821/478', 'Danieltown/HI', '(525)270-5408', 'Masters', '2029-03-09', 3),
    ('Electrical Engineering', 'Gray University', 'https://dummyimage.com/946x1005', 'South Brittney/PW', '001-878-912-4640x8915', 'PHD', '2030-03-10', 10),
    ('Computer Engineering', 'Johnson University', 'https://placekittens.com/753/23', 'New Andrewchester/IL', '(322)263-1079x81788', 'Masters', '2027-09-26', 27),
    ('Computer Scinece', 'Oliver University', 'https://picsum.photos/728/587', 'West Lauren/MP', '(840)860-3184x80228', 'Bachelors', '2025-06-06', 16),
    ('Computer Engineering', 'Kaiser University', 'https://picsum.photos/44/969', 'Sarahaven/NC', '001-448-447-4333', 'Bachelors', '2030-01-16', 28),
    ('Chemistry', 'Hughes University', 'https://placekittens.com/741/892', 'Fitzgeraldborough/KY', '+1-948-459-1066x565', 'PHD', '2025-08-16', 13),
    ('Mechanical Engineering', 'Becker University', 'https://placekittens.com/233/501', 'Hunterstad/NC', '2863008003', 'PHD', '2026-04-29', 6),
    ('French Literature', 'Booth University', 'https://placekittens.com/69/975', 'West Wayneberg/OR', '2457818243', 'Bachelors', '2029-06-29', 26),
    ('Computer Engineering', 'James University', 'https://dummyimage.com/957x809', 'North Matthew/UT', '+1-332-401-2753x20471', 'Masters', '2030-04-02', 18),
    ('Mathematics', 'French University', 'https://dummyimage.com/390x392', 'Vegaburgh/KS', '001-565-754-7697x443', 'PHD', '2025-07-11', 29),
    ('Computer Engineering', 'Hampton University', 'https://picsum.photos/826/433', 'Wrightbury/NJ', '001-987-581-6350x51285', 'Bachelors', '2029-09-04', 22),
    ('Electrical Engineering', 'Higgins University', 'https://picsum.photos/395/31', 'Taylorview/LA', '(608)898-1340x28364', 'Masters', '2026-04-27', 18),
    ('History', 'Smith University', 'https://dummyimage.com/1020x271', 'Willietown/MH', '+1-592-867-8115', 'Bachelors', '2028-06-10', 7),
    ('French Literature', 'Chapman University', 'https://picsum.photos/377/498', 'Brianhaven/VA', '001-589-981-2937', 'PHD', '2030-02-12', 25),
    ('Data Science', 'Patel University', 'https://picsum.photos/871/631', 'Millerview/WI', '+1-741-694-1074', 'Bachelors', '2025-04-30', 3),
    ('Data Science', 'Hall University', 'https://placekittens.com/493/251', 'Nguyenmouth/MH', '760-434-3442', 'Bachelors', '2027-01-28', 10),
    ('Data Science', 'Franco University', 'https://dummyimage.com/835x818', 'New Tonyview/CO', '3583114503', 'Bachelors', '2027-11-13', 20),
    ('Electrical Engineering', 'Higgins University', 'https://picsum.photos/760/839', 'East Crystal/CO', '(288)354-9647x16232', 'PHD', '2027-12-21', 5),
    ('History', 'Hanson University', 'https://placekittens.com/403/563', 'Dianaton/PW', '663.728.2573', 'Bachelors', '2025-06-03', 3),
    ('Chemistry', 'Shields University', 'https://placekittens.com/160/143', 'Port Danielborough/KS', '+1-758-973-7772x91840', 'Bachelors', '2026-09-18', 18),
    ('Electrical Engineering', 'Reyes University', 'https://placekittens.com/268/1001', 'Lake Paulfort/NE', '001-863-321-7833x7031', 'Bachelors', '2027-05-05', 30),
    ('Computer Scinece', 'Franklin University', 'https://picsum.photos/491/24', 'North Stacey/ID', '001-712-892-2050x161', 'Masters', '2026-12-03', 10),
    ('Computer Engineering', 'Garcia University', 'https://dummyimage.com/138x80', 'North Kimberly/WA', '001-644-368-1658x50588', 'Masters', '2029-12-22', 7),
    ('Data Science', 'Dalton University', 'https://dummyimage.com/996x5', 'North Lancefort/PA', '3005037398', 'Bachelors', '2029-08-19', 24);

INSERT INTO job_posters (company_name, industry, user_id) VALUES
    ('Zimmerman Group', 're-contextualize enterprise mindshare', 21),
    ('Jones, Turner and Stewart', 'target collaborative e-markets', 1),
    ('Boyd-Martinez', 'transform killer action-items', 9),
    ('Reed, Allen and Johnson', 'architect plug-and-play channels', 12),
    ('Hall Ltd', 'evolve vertical systems', 25),
    ('Martin, Anderson and Wells', 'unleash robust technologies', 8),
    ('Payne PLC', 're-contextualize B2C e-commerce', 24),
    ('Hamilton, Lynch and Nichols', 'utilize next-generation interfaces', 30),
    ('Gomez, Sullivan and Gonzales', 'engineer B2C e-services', 3),
    ('Hester Inc', 'integrate holistic e-business', 14),
    ('Martin, Ward and Collins', 'e-enable one-to-one initiatives', 29),
    ('Gordon, Mendez and Yu', 'repurpose dynamic users', 1),
    ('Macias-Leonard', 'mesh global web-readiness', 19),
    ('Berry-Savage', 'leverage customized communities', 21),
    ('Rodriguez Inc', 're-intermediate revolutionary ROI', 21),
    ('Weeks-Perry', 'target customized bandwidth', 20),
    ('Warner-Ball', 'innovate collaborative networks', 17),
    ('Tucker-Robinson', 're-contextualize web-enabled e-services', 3),
    ('Bowman-Sawyer', 'synergize value-added supply-chains', 14),
    ('Coffey, Nelson and Griffin', 'harness wireless action-items', 2),
    ('Garcia Ltd', 'transition next-generation technologies', 30),
    ('Miller, Foster and Shaw', 'integrate turn-key relationships', 4),
    ('Collins-Ramos', 'envisioneer user-centric web services', 18),
    ('Johnson, Ingram and Villanueva', 'disintermediate interactive users', 6),
    ('Berry, Santiago and Warner', 'repurpose value-added deliverables', 7),
    ('Wilson Ltd', 'generate best-of-breed infrastructures', 17),
    ('Eaton Inc', 'seize cross-media e-markets', 1),
    ('Solomon, Strickland and Salazar', 'visualize world-class content', 23),
    ('Long-Brennan', 'visualize killer e-markets', 15),
    ('Davis LLC', 'scale revolutionary portals', 29);

INSERT INTO company_websites (poster_id, website_link) VALUES
    (29, 'https://www.yang-johnson.com/'),
    (30, 'http://www.nichols.info/'),
    (15, 'http://anderson.com/'),
    (9, 'http://miller.com/'),
    (25, 'https://www.sanders.com/'),
    (9, 'https://www.james-lang.com/'),
    (1, 'http://www.buck-white.biz/'),
    (9, 'http://smith.com/'),
    (19, 'http://www.harris.com/'),
    (20, 'http://middleton-sutton.com/'),
    (3, 'https://www.powell.com/'),
    (11, 'https://www.freeman.com/'),
    (8, 'https://brown.info/'),
    (28, 'https://www.miller.com/'),
    (17, 'https://www.white.com/'),
    (8, 'http://www.key.com/'),
    (6, 'http://moreno.com/'),
    (9, 'http://www.wright.com/'),
    (5, 'http://www.riley-guerra.biz/'),
    (29, 'http://www.novak.com/'),
    (5, 'http://www.sanchez-harvey.info/'),
    (29, 'http://blackwell.com/'),
    (10, 'https://www.byrd.com/'),
    (29, 'http://sutton-rios.com/'),
    (29, 'https://barber-norris.com/'),
    (27, 'https://davis.info/'),
    (29, 'https://anderson.com/'),
    (28, 'https://smith.com/'),
    (5, 'http://houston.org/'),
    (2, 'http://morgan.org/'),
    (16, 'http://bass.com/'),
    (11, 'http://www.williams-mcintosh.biz/'),
    (21, 'https://peterson.info/'),
    (22, 'https://hess-thomas.com/'),
    (2, 'http://www.perez-bell.biz/'),
    (19, 'http://cox.net/'),
    (2, 'http://espinoza.com/'),
    (19, 'https://mahoney-thomas.com/'),
    (17, 'http://www.alexander.com/'),
    (19, 'https://www.kaufman.org/');

INSERT INTO resumes (education, work_experience, personal_project, hobby, author_id) VALUES
    ('Why ahead something bag. Figure turn father color save type.', 'Popular husband yourself institution anyone. We still gas year international institution attention. Candidate true over magazine Republican heavy.', 'Those decade issue second low. Discover single according threat fly at election.', 'Whose actually low degree measure opportunity role. Cover from life either.', 12),
    ('Democratic suffer around watch budget week. Benefit today light arrive purpose design quality. Close few radio only common tend.', 'Subject law although animal. Foreign run paper dinner.', 'Difficult show maybe wonder send. Magazine lose include hold decade Democrat audience. Whom difficult you share activity message.', 'Property his left story whose word significant. Among wear behavior final general heavy per. Beautiful thus blood offer. Small subject occur scientist.', 8),
    ('Several main question memory manager soon medical. Ago mind month. Door wife early purpose threat work.', 'She such involve fly unit dark occur. Seek goal project quite pressure assume window. Himself spring wall can.', 'Weight wall laugh. Picture many author price likely quite. Fight heavy resource. Car perform beautiful.', 'Material network leave own west. Daughter represent across final.', 25),
    ('Age prepare relate happy across. No child religious interest win market require. Short dream increase others improve his effect focus. Ten practice necessary national.', 'Region meeting environmental always might. Community owner lot bring degree across stuff. Then technology people night increase Republican forward letter.', 'Simply us fly. Ask couple shake behavior raise. Do seem body among other particularly. Information identify seem decade always.', 'Role enough loss kid nothing behavior. Site upon seven interview occur not evidence customer. Manage century one public join. Before several like relate president.', 2),
    ('Enjoy rich most mean.', 'Summer catch treat address. Spring president support personal side phone. Stand have fine top former.', 'People dog miss put firm. If capital citizen. Agent wide reach so left young activity.', 'Oil federal cup firm usually game. Live entire key degree must. Peace beat hold yourself agency policy system.', 30),
    ('Actually add common friend. Not reason certainly.', 'Wife soldier collection personal coach worker. Reach significant concern season that beyond other.', 'Response agency coach carry career last show difference. Even offer hard stage final able speech.', 'International method less himself increase magazine yet. Break blue large provide one. Room mouth spend like black.', 18),
    ('Series front moment idea. Lead economic care ability board down his.', 'Few lawyer air all. In growth particularly fly father almost baby. Service Mr assume Republican glass.', 'Old radio only health similar oil door. Two difficult performance cause. Suddenly follow feeling include.', 'Approach writer explain occur claim compare thank life. Happen direction different same. Career food choice coach miss majority.', 30),
    ('Hear edge organization picture money human. Partner up system well. Help president technology difficult hold onto.', 'Those large age much poor second. Position international sound future bill soon society.', 'Arrive specific pick necessary. About animal loss miss section fine. Likely education prove important three fish.', 'It land here however what apply. Performance analysis daughter soon sister. Start act firm best.', 29),
    ('Land voice certain again with team thousand. Onto scene kid positive choice. Sea lead as huge together center since.', 'Example front member. Accept manage cut including under. Indeed finish push her result.', 'For forget vote product of believe money suddenly. Cause treatment cold market. Less quickly a pick.', 'Realize official place raise. Stock western consider even.', 20),
    ('Sport condition provide card. Rock pay mind sometimes project face step truth. Bank south human network.', 'Truth wear arrive source common life form. Explain program soon worker drug life. Wonder world up tax though town relationship.', 'Itself including business hotel. Present that vote above.', 'Physical five defense type under number training morning. Table bed citizen of once role.', 16),
    ('Institution computer hour lose management certain stop. Culture wind strong thought.', 'Employee agency by interesting official. Put health against along budget thus.', 'No huge eight throughout job. Road probably assume throw daughter go west. Interview woman firm leave. Why it will expect.', 'Design receive resource type. Arrive establish serve attention. Past field rock yes mean check.', 23),
    ('Several treat before allow recognize. Business likely effort wish.', 'View table early wear all public in answer. Inside community wide class most think shake. Very already alone somebody.', 'Voice town sense truth. War evidence say century cause player. Former truth determine the nor.', 'Need citizen church. Program save such.', 10),
    ('Use citizen outside recent. Necessary according would light.', 'Strong rich knowledge number their. Whether find buy hotel experience when different. Size writer whom include direction course prove. Sure join reality receive affect image.', 'Politics office box technology. You new writer ready green law maintain. While or even pass write.', 'Such discuss kitchen music. Forward in share month many church including.', 19),
    ('Agreement very person social couple option. Health which here statement money audience mention financial. Until product player stock according task rest specific.', 'Stock traditional interview fire choose relate question. Arm home reach real style tonight method.', 'Actually story plan pick true learn month. Party finally center south.', 'Such across stuff middle she effect campaign. Only raise eat wear.', 20),
    ('Accept push behavior kid drop nearly. Upon baby end just play.', 'Through relationship describe model direction carry scene. Analysis drug plant better question speak pass big. Pressure base anyone write really.', 'Simple growth the loss too. Allow son left eat consider wife. Often resource thank then according key attorney.', 'Consumer should bring market although. Forward president picture politics inside PM. Group Mrs worry.', 11),
    ('Nor keep movie we develop could act. Key shoulder away describe. American technology affect material than.', 'Necessary difference finally culture discuss president network not. Politics own across thing.', 'Hard blood left two. Arrive newspaper west use social program citizen.', 'Exactly similar relate couple wish how city. Watch sing unit risk somebody measure.', 13),
    ('Base task meeting knowledge. Apply until network discuss likely down.', 'Exactly organization catch. Figure area among reality.', 'Language believe view management inside. Attention candidate do serve scientist single clear. Picture Mr economic evening sister tonight. Evidence beyond three certain.', 'Turn hear skin give. Join discover thought establish perform.', 29),
    ('Adult traditional hold. Agreement security hair claim. Law serious event cut.', 'Chance sport seem western. Realize economic rather news skill try human game. General fall away see.', 'Common born audience information send buy design. News could south true trouble food child. Me ability establish section spend.', 'Write traditional seem alone eat story. What skin world direction.', 21),
    ('Democratic hot against continue purpose.', 'Long rich maintain note ok. Financial cell room part dog. Probably beyond five site until stay. Moment two general establish.', 'Such live consider sea. Hotel light whose choice team young.', 'Beyond choose design away either reflect. Development media find adult. Like describe second police popular short three.', 2),
    ('I identify fund skin impact themselves require.', 'Science give peace defense election customer half.', 'Wall rise ahead even. Respond above into perhaps own.', 'Someone something old test onto. Military expert through great. Employee voice chance skin energy article city region.', 14),
    ('Responsibility particularly resource condition toward. Inside argue economy anything impact debate teach person. Agreement business role structure wear.', 'At while since beat into military rather he. Fine perhaps middle prevent assume.', 'Last site third affect society head art. Take from somebody security young decide education.', 'Hear house oil exactly should hotel down. Senior run out major radio. Speak certain method radio animal.', 16),
    ('Team light hair see. Child admit become card simply American continue. Teacher past plant hit challenge institution.', 'Follow different step. Nation night trip serve after close.', 'Public end side spring important finish former. Debate information read message.', 'Road themselves seek job. Step buy cell. Arm bad news fly.', 22),
    ('Beyond stock spring traditional stuff office red interesting. Different rule begin left.', 'With threat benefit experience but natural. Half wife either over. Large thus question later worry exist sense.', 'Reflect herself meet employee bad base agree. Health product always stage notice whatever. Culture food senior six discussion.', 'Trip kitchen woman sense left feel. Indicate herself hot walk enough who.', 26),
    ('Man spend goal describe design. Hand single foreign collection system speak project. Federal left discover beautiful responsibility teacher service.', 'Military concern south nature. Author cold bank prove. About mouth also anyone here some as.', 'Become similar picture risk product significant car. Dinner science good line major.', 'Effect deal field figure. Act college game past interview wall speech authority. Care goal ever say exactly.', 17),
    ('Trial past candidate ball practice cup different. Cut third risk vote become ok attorney. Form unit hand onto claim owner.', 'Party sister compare worry figure better statement. Clear six wait happy five. Eye prove perhaps paper on someone day. Reach wind actually statement budget.', 'Inside story thing certainly method remain control. Republican free simply again face.', 'Fast thought state meet human assume. Test sister build we. Start site including year nor.', 16),
    ('Card prepare page into anyone suddenly. Attention research form present arrive.', 'Evidence if approach best million evidence. Government hope military.', 'Little rise discover sense behavior because give. Fear real own note short. Bar need bar maintain drug.', 'Have political message push expect example huge. Similar measure who number.', 27),
    ('Item hundred instead maintain night. Develop yard enjoy final save project we work. About health form.', 'Focus theory go audience ever institution me. Reach partner add enter.', 'Theory mission never knowledge. Simple must behind size should. Blue agree among economy week.', 'Leave have approach issue discover. Term world turn machine figure scene.', 29),
    ('Country entire business family through miss mind. Hospital item dream yet.', 'Possible part provide water figure sense read cold. Animal peace key mean policy.', 'Rest trouble already let finish trial suggest. Form together although. Technology born imagine us.', 'Believe door notice notice ready. Knowledge expert hundred use author.', 10),
    ('Again to kitchen realize time class. Military impact conference style similar push like toward. Professor similar should federal huge decision we.', 'Drop close customer oil. Knowledge alone only face.', 'Wind family responsibility million suffer charge. Standard next figure must woman recognize. Improve garden type plant response loss property.', 'But recent many. Song fill executive act business. Everything message gun.', 10),
    ('Among financial improve world others. Keep live these shoulder. Management campaign usually class team. Most answer issue piece either firm soldier.', 'Seven from specific. Money usually build common model. Leader local reveal act. Stand force building agent.', 'Get them southern air. Surface before democratic.', 'Stop course always. Whole learn star such scientist.', 9);

INSERT INTO personal_websites (resume_id, website) VALUES
    (27, 'https://roman.info/'),
    (29, 'http://www.garcia.org/'),
    (15, 'http://evans-baker.com/'),
    (14, 'http://www.russell.com/'),
    (8, 'http://carter-griffin.com/'),
    (30, 'https://gill.net/'),
    (13, 'http://www.king.com/'),
    (5, 'http://lee.info/'),
    (10, 'https://weber.com/'),
    (4, 'https://www.miller-mcclain.info/'),
    (21, 'https://fisher.biz/'),
    (15, 'https://www.robinson.info/'),
    (30, 'http://www.dodson.net/'),
    (9, 'https://www.mullins-perry.com/'),
    (14, 'http://rodriguez-miller.org/'),
    (3, 'https://dawson.com/'),
    (24, 'http://www.cook.com/'),
    (29, 'https://frank.com/'),
    (17, 'https://www.sanchez-williams.com/'),
    (10, 'http://www.brown.com/'),
    (4, 'https://sanders.org/'),
    (14, 'http://www.pacheco.com/'),
    (17, 'http://cantu-dunlap.net/'),
    (29, 'https://www.martinez.com/'),
    (11, 'http://yu.com/'),
    (27, 'https://gutierrez.info/'),
    (3, 'http://www.johnson-vargas.org/'),
    (16, 'http://www.wilson-pacheco.net/'),
    (25, 'https://www.williams.biz/'),
    (7, 'https://www.mathews.net/'),
    (16, 'https://jordan.info/'),
    (3, 'https://www.good.com/'),
    (16, 'https://www.torres.com/'),
    (22, 'https://hoffman.net/'),
    (11, 'https://www.summers.com/'),
    (13, 'https://www.barry.com/'),
    (29, 'http://byrd.biz/'),
    (24, 'http://henry.com/'),
    (3, 'https://www.diaz-ortiz.com/'),
    (20, 'https://morris.com/');

INSERT INTO system_logs (error_code, error_description, resolved_at, resolution_status, creator_id) VALUES
    ('UniWorks Provider Error', 'Issue name possible body as phone color fly.', '2025-05-25', 'Resolved', 20),
    ('UniWorks Provider Error', 'Cup color radio movement.', '2025-07-25', 'In progress', 19),
    ('UniWorks Provider Error', 'Memory news we.', '2026-02-20', 'In progress', 25),
    ('UniWorks Provider Error', 'Into season spring lead probably.', '2025-09-07', 'In progress', 30),
    ('UniWorks Provider Error', 'Measure opportunity pretty other.', '2025-12-22', 'In progress', 18),
    ('UniWorks Provider Error', 'Stuff thing seat contain long cut.', '2026-04-17', 'In progress', 26),
    ('UniWorks Provider Error', 'Their power community response prepare.', '2025-10-13', 'Started', 6),
    ('UniWorks Provider Error', 'Easy husband theory family firm police popular young.', '2026-03-04', 'Started', 7),
    ('UniWorks Provider Error', 'Operation effect indicate raise key long.', '2026-01-16', 'In progress', 8),
    ('UniWorks Provider Error', 'Game social size most.', '2025-08-28', 'Resolved', 28),
    ('UniWorks Provider Error', 'Difficult true organization focus serious move.', '2025-05-08', 'Resolved', 20),
    ('UniWorks Provider Error', 'Fight indicate manage top tree.', '2025-05-05', 'In progress', 18),
    ('UniWorks Provider Error', 'Accept thank world writer finish budget quite.', '2025-05-09', 'Resolved', 7),
    ('UniWorks Provider Error', 'By small Republican major.', '2025-08-29', 'Resolved', 23),
    ('UniWorks Provider Error', 'Son benefit draw Congress general difference adult.', '2025-04-27', 'In progress', 12),
    ('UniWorks Provider Error', 'Air analysis teach store.', '2026-02-21', 'In progress', 17),
    ('UniWorks Provider Error', 'Help black message mean.', '2026-02-19', 'In progress', 21),
    ('UniWorks Provider Error', 'Pm for eye cut board how soon group.', '2025-12-13', 'In progress', 4),
    ('UniWorks Provider Error', 'Order win scientist age.', '2025-10-31', 'In progress', 23),
    ('UniWorks Provider Error', 'Necessary win possible yourself business.', '2025-06-13', 'Started', 8),
    ('UniWorks Provider Error', 'Life everything finally between movement vote base.', '2025-12-18', 'Resolved', 26),
    ('UniWorks Provider Error', 'President another inside few human relate.', '2025-12-10', 'Resolved', 9),
    ('UniWorks Provider Error', 'Left right mind mission entire senior.', '2025-07-24', 'Started', 3),
    ('UniWorks Provider Error', 'Relate material oil head matter loss.', '2025-12-29', 'Resolved', 14),
    ('UniWorks Provider Error', 'Republican movie know east add firm.', '2025-06-15', 'In progress', 14),
    ('UniWorks Provider Error', 'Site traditional test street speech carry.', '2025-05-04', 'In progress', 23),
    ('UniWorks Provider Error', 'Prove wear respond him star.', '2026-03-11', 'Resolved', 27),
    ('UniWorks Provider Error', 'Say film same car.', '2025-07-17', 'In progress', 8),
    ('UniWorks Provider Error', 'Many push then heart.', '2025-05-20', 'In progress', 4),
    ('UniWorks Provider Error', 'Lawyer across bag network media.', '2025-04-20', 'In progress', 4);

INSERT INTO job_posts (job_title, job_salary, job_description, job_duration, city_state, attendance_type, poster_id) VALUES
    ('Risk manager', 22.7, 'Reduce perform note step care cause prevent herself. Need edge easy six once difficult medical. Customer say art blood dark let.', 'Internship', 'South Brettbury/FM', 'Hybrid', 10),
    ('Hospital doctor', 31.55, 'So man seat sell. Name full whatever.', '8-Month COOP', 'South Jessicastad/CT', 'On-site', 21),
    ('Barrister', 23.39, 'Responsibility interesting author some nation carry catch. Build green court miss material process.', '6-Month COOP', 'Michaelshire/VI', 'Remote', 9),
    ('Database administrator', 27.9, 'Provide send report several store more. One save source themselves technology home region. Pick current available sport eight claim.', 'Internship', 'East Davidland/NY', 'Hybrid', 20),
    ('Chief Operating Officer', 24.34, 'Fear over mean contain put book happy. We despite play message of economy.', '8-Month COOP', 'Nathanville/WV', 'On-site', 29),
    ('Health physicist', 20.59, 'Anything hard some traditional southern least night. Religious ok hope everyone tough since teacher. Book debate gas without reality son year.', '4-Month COOP', 'New Sarah/NH', 'On-site', 7),
    ('Surveyor, building control', 24.76, 'Heavy guess how effect. Manager market analysis site. Program doctor method prevent.', 'Internship', 'Port Patricia/AL', 'Hybrid', 26),
    ('Insurance claims handler', 34.96, 'Easy growth ready she. Race build after college individual.', '6-Month COOP', 'Kimberlyville/IA', 'Remote', 7),
    ('Engineer, electronics', 33.89, 'Air school ground institution finish from attorney. Probably inside sit race measure. Forget go choice already national ok attack offer.', 'Internship', 'East Sandra/NH', 'Remote', 28),
    ('Geophysical data processor', 20.32, 'Leader already drop certain travel guess loss.', '8-Month COOP', 'Spencermouth/LA', 'Hybrid', 13),
    ('Pharmacist, community', 23.68, 'Nice school recent art great want. Outside play part material energy man.', '6-Month COOP', 'Frankburgh/DC', 'Remote', 23),
    ('Neurosurgeon', 18.38, 'Use region surface hot front central. Upon accept never follow for mother my involve. Eight easy cause important. Always power training kid.', '6-Month COOP', 'Lake Anitamouth/MH', 'Hybrid', 21),
    ('Media buyer', 21.6, 'Into low raise list direction conference writer. Study wall me race will actually. Director condition official true suffer result.', 'Internship', 'North Amandaburgh/DC', 'On-site', 2),
    ('Conference centre manager', 24.99, 'Green could himself name. Hold wind sea more past. Truth arrive nice civil production specific agent.', 'Internship', 'Amyfurt/OK', 'Remote', 5),
    ('Management consultant', 33.32, 'Decision daughter evening matter a hit memory indeed.', 'Internship', 'Christopherstad/PR', 'On-site', 5),
    ('Publishing rights manager', 23.55, 'Partner leg year decision raise soldier pretty director. Guess woman marriage tough practice half.', '6-Month COOP', 'Kristineborough/AK', 'On-site', 27),
    ('Theatre director', 22.91, 'Job debate billion none north middle. Where many station.', 'Internship', 'Walkerland/AS', 'On-site', 22),
    ('Health visitor', 31.43, 'Serve floor strategy very sport source why choice. Cup give benefit family.', '6-Month COOP', 'Justinfurt/AZ', 'Hybrid', 9),
    ('Emergency planning/management officer', 21.83, 'More evening certain management. Here prove front wonder how second his. Production determine doctor house add fish.', '4-Month COOP', 'Mcintyrefurt/UT', 'On-site', 29),
    ('Insurance account manager', 23.51, 'Place break measure industry vote article box. Chair sea sure sing paper current whose. Charge stay two fill off medical type such.', '6-Month COOP', 'Robertstad/WY', 'Hybrid', 29),
    ('Engineer, manufacturing', 23.24, 'Customer three ground dark very budget eight political. Western deep official few. Ball sit provide network push.', 'Internship', 'North Mercedes/NV', 'On-site', 2),
    ('Teacher, early years/pre', 28.34, 'Until local focus represent sure. Exactly quite deal realize home. Cell adult red church agree.', '8-Month COOP', 'West Annafort/DE', 'Hybrid', 25),
    ('Buyer, retail', 19.09, 'Spring best nothing federal. American citizen heavy news mention. Dinner contain analysis half.', '4-Month COOP', 'Hollyland/NE', 'Hybrid', 24),
    ('Location manager', 32.14, 'Herself current account. Positive guy end race any.', '8-Month COOP', 'Grahamshire/IN', 'Hybrid', 8),
    ('Theatre manager', 21.95, 'Low tax challenge student score owner old figure. Official training ability.', '4-Month COOP', 'Acostaville/FL', 'Hybrid', 1),
    ('Medical laboratory scientific officer', 21.57, 'Answer history indicate operation son. Class identify enough position.', '6-Month COOP', 'West Michaelmouth/LA', 'Remote', 25),
    ('Science writer', 24.1, 'Center machine talk American industry why else. Truth day pass sport first society hot new.', 'Internship', 'Juareztown/IA', 'Hybrid', 5),
    ('Production designer, theatre/television/film', 21.49, 'Later cell down wind. Central outside leave can successful car final. Rate parent box above green beyond election.', '6-Month COOP', 'New Stephaniechester/OH', 'Remote', 18),
    ('Production assistant, television', 32.43, 'Performance plan decide history check store pretty system. Wonder would writer threat structure. Still role but your. Within eat road region sound.', 'Internship', 'South Christine/GU', 'On-site', 27),
    ('Orthoptist', 22.71, 'Quality business information staff act. Month case nature huge partner require political.', '4-Month COOP', 'East Dariusville/MA', 'Hybrid', 16);

INSERT INTO job_links (post_id, job_link) VALUES
    (9, 'http://miller-johnson.com/'),
    (29, 'https://www.peck.net/'),
    (19, 'https://smith.net/'),
    (23, 'https://www.orozco.com/'),
    (15, 'http://price.com/'),
    (10, 'http://parker-herring.com/'),
    (2, 'http://www.combs.com/'),
    (13, 'http://matthews-schultz.com/'),
    (13, 'https://www.hughes.org/'),
    (30, 'https://clark.com/'),
    (17, 'http://www.huber.net/'),
    (5, 'http://www.parsons-castillo.com/'),
    (22, 'http://www.martin-dean.com/'),
    (22, 'https://www.mcbride.org/'),
    (5, 'http://moore-hoover.info/'),
    (13, 'http://www.johnson-mata.org/'),
    (19, 'https://james.com/'),
    (19, 'https://www.gordon-webb.com/'),
    (7, 'http://www.fowler-graham.com/'),
    (21, 'http://diaz-velasquez.com/'),
    (9, 'http://turner.com/'),
    (14, 'https://nielsen-white.com/'),
    (13, 'http://www.tyler.net/'),
    (30, 'http://www.simmons.info/'),
    (7, 'http://cherry-may.com/'),
    (27, 'http://vaughn-whitney.com/'),
    (24, 'https://berger-fields.com/'),
    (18, 'http://www.wagner-frank.com/'),
    (27, 'http://www.ramos.biz/'),
    (20, 'http://gibson.com/'),
    (9, 'https://www.barnes-good.com/'),
    (30, 'https://haas-simmons.com/'),
    (16, 'https://davis-mendoza.info/'),
    (17, 'https://www.chan.info/'),
    (27, 'https://cooley.com/'),
    (18, 'http://sheppard.com/'),
    (18, 'http://hernandez-roberts.com/'),
    (19, 'https://www.hawkins.com/'),
    (2, 'https://www.williams.net/'),
    (7, 'http://sanchez-kelly.info/');

INSERT INTO job_limits (max_count, college, min_gpa, university, job_id) VALUES
    (46, 'Snyder College', 3.48, 'Smith University', 18),
    (40, 'Anderson College', 3.2, 'Cardenas University', 13),
    (5, 'Hanson College', 2.03, 'Carpenter University', 21),
    (46, 'Case College', 3.39, 'Lam University', 18),
    (9, 'Henderson College', 0.91, 'Spencer University', 5),
    (10, 'Middleton College', 0.45, 'Cross University', 10),
    (19, 'Lowery College', 3.5, 'Burke University', 14),
    (3, 'Yu College', 1.98, 'Maldonado University', 28),
    (43, 'Clark College', 0.69, 'Lopez University', 11),
    (2, 'Strickland College', 3.45, 'Hill University', 19),
    (27, 'Morgan College', 1.61, 'Fry University', 11),
    (50, 'Jones College', 0.77, 'Murray University', 2),
    (45, 'Hernandez College', 1.97, 'Shepherd University', 16),
    (18, 'Morales College', 3.31, 'Alexander University', 1),
    (5, 'Potter College', 1.94, 'Livingston University', 28),
    (12, 'Cummings College', 0.17, 'Brown University', 13),
    (41, 'Crawford College', 2.72, 'Nelson University', 18),
    (18, 'Brennan College', 3.81, 'Deleon University', 2),
    (11, 'Clark College', 0.61, 'Flores University', 9),
    (48, 'Castillo College', 3.78, 'Griffith University', 18),
    (6, 'Arias College', 1.36, 'Davis University', 22),
    (39, 'Moran College', 0.18, 'Spears University', 29),
    (38, 'Walton College', 0.58, 'Alexander University', 3),
    (3, 'Rivera College', 1.03, 'Graham University', 16),
    (21, 'Allen College', 2.17, 'Todd University', 28),
    (41, 'Hunt College', 1.28, 'Carney University', 14),
    (17, 'Harrington College', 2.96, 'Greer University', 22),
    (35, 'Dixon College', 3.81, 'Craig University', 18),
    (26, 'Gilbert College', 3.73, 'Ware University', 1),
    (3, 'Mcdowell College', 0.01, 'Ward University', 19);

INSERT INTO applications (cover_letter, stage, status, application_date, applicant_id, job_id, resume_id) VALUES
    ('Billion one firm detail yourself be another. Director fall such me relationship whatever white.', 'Offer', 'Unknown', '2025-06-04', 28, 19, 7),
    ('Return fill phone letter. Report specific brother push who.', 'Applied', 'Rejected', '2025-10-01', 20, 30, 16),
    ('Yourself its eight about grow choice indeed start. House some thousand wife two speech.', 'Offer', 'Rejected', '2025-12-24', 15, 17, 8),
    ('Hair city present push series small listen. Summer past court himself. Few interesting important management indicate national nation.', 'Applied', 'Rejected', '2025-06-28', 14, 28, 2),
    ('Hear discover worker some us down. Song would magazine evening risk. Dinner step conference system attention.', 'Applied', 'Ghosted', '2026-03-20', 14, 12, 18),
    ('Investment and seem air on possible. School none article soon. Player one visit tend.', 'Interview', 'Ghosted', '2025-12-21', 15, 20, 18),
    ('Avoid benefit budget receive. Animal less note training away. Region many sport.', 'Offer', 'Ghosted', '2026-02-02', 1, 27, 18),
    ('Audience idea up rise condition design however. Catch score write among consumer figure more fact. Hospital interest middle participant never affect which.', 'Applied', 'Ghosted', '2025-07-12', 5, 20, 14),
    ('Thank environment arm. Resource check early idea whether director film.', 'Interview', 'Rejected', '2026-03-25', 18, 15, 1),
    ('Them laugh fire police look. Ball million century interview miss work. Federal executive budget start collection sound rather.', 'Offer', 'Accepted', '2026-03-08', 5, 6, 8),
    ('Discuss computer training quickly give current this. Analysis herself return enter.', 'Offer', 'Unknown', '2025-06-30', 6, 19, 7),
    ('None property offer goal. Class particularly in issue station seven.', 'Interview', 'Unknown', '2025-08-06', 4, 27, 14),
    ('Health try help development. American ready thousand.', 'Interview', 'Unknown', '2025-10-08', 7, 13, 9),
    ('Difficult point senior poor. Brother health political finish teach.', 'Applied', 'Unknown', '2025-07-26', 28, 24, 15),
    ('Decision wonder wife never.', 'Interview', 'Accepted', '2025-08-16', 18, 11, 10),
    ('Star may military able whom wide maintain. Blue create president beautiful million see really message. Others sometimes family establish PM decision support happy.', 'Offer', 'Accepted', '2025-10-18', 28, 20, 20),
    ('Camera read upon pay difference visit.', 'Offer', 'Ghosted', '2025-09-24', 30, 21, 2),
    ('Congress else team cell. Say walk which wide return that book. Discover prove wide she.', 'Interview', 'Ghosted', '2026-04-13', 18, 24, 8),
    ('Ago involve stay west. Sell important nature quality she fast collection.', 'Interview', 'Accepted', '2025-11-29', 26, 13, 16),
    ('Nor performance wall rich responsibility right.', 'Interview', 'Unknown', '2025-05-19', 4, 30, 3),
    ('Your should allow cell explain. Technology value price art good ready total base. Hope camera unit alone.', 'Applied', 'Ghosted', '2026-04-05', 7, 22, 24),
    ('Bit staff week base receive. Eight me fact foreign whether any. Blood whom cause lay step style.', 'Interview', 'Waiting', '2026-02-21', 6, 19, 21),
    ('Hospital thus move east try. Under out whether happy behind could.', 'Offer', 'Waiting', '2025-10-16', 7, 9, 13),
    ('First news record remember yes fly idea beautiful. Source very industry fear or.', 'Offer', 'Accepted', '2025-05-18', 18, 26, 5),
    ('Paper without history across nor. Ability once personal couple source him safe.', 'Applied', 'Rejected', '2026-03-20', 9, 18, 18),
    ('As inside American leg push course remain buy. Choose join what trip money.', 'Applied', 'Accepted', '2026-01-17', 8, 14, 28),
    ('Million cell international field decision poor idea. Simple billion within its dream. Adult religious image choose.', 'Offer', 'Unknown', '2025-10-25', 3, 24, 1),
    ('Assume order very value go sell. President foot member. National phone skin total specific whose range.', 'Interview', 'Waiting', '2026-03-23', 27, 1, 12),
    ('Try network just like. Experience population brother song.', 'Offer', 'Ghosted', '2025-09-02', 8, 9, 20),
    ('Personal movie sit value enjoy just great window. Natural positive forward deal whole interview area pull.', 'Offer', 'Rejected', '2025-07-16', 6, 27, 13);

INSERT INTO activities (activity_date, notes, type, status, application_id) VALUES
    ('1977-03-03 05:56:45', 'Follow growth create military.', 'Tour', 'Unknown', 25),
    ('1996-09-08 09:27:42', 'Fear range phone any yard what.', 'Tour', 'Unknown', 20),
    ('1995-02-02 13:18:05', 'Upon voice society name color.', 'Technical Interview', 'Unknown', 14),
    ('1972-07-30 13:48:09', 'Sit before dream population.', 'Behavioral Interview', 'Ghosted', 17),
    ('2025-02-02 01:20:35', 'Employee right want brother middle here civil.', 'Tour', 'Waiting', 14),
    ('1992-05-22 21:54:38', 'Green behavior challenge these travel.', 'Technical Interview', 'Waiting', 13),
    ('2001-07-20 10:02:53', 'Decision use any guess.', 'Behavioral Interview', 'Unknown', 28),
    ('2016-03-02 11:13:01', 'Off dog attention play hour want.', 'Technical Interview', 'Rejected', 23),
    ('1991-03-27 19:28:31', 'Though though hold low minute.', 'Tour', 'Ghosted', 12),
    ('1979-12-01 00:16:40', 'Miss research least word station.', 'Behavioral Interview', 'Unknown', 12),
    ('1982-08-08 21:43:12', 'During know camera if a yourself.', 'Behavioral Interview', 'Waiting', 21),
    ('1983-09-09 01:06:31', 'Expect least remember Mrs direction create north bed.', 'Tour', 'Accepted', 6),
    ('1977-10-27 11:19:55', 'Manager service hope one.', 'Tour', 'Accepted', 11),
    ('1985-03-04 22:31:42', 'Manage perform art treatment conference.', 'Tour', 'Rejected', 9),
    ('2007-04-24 21:01:08', 'Race clear tree reality expert start this.', 'Technical Interview', 'Ghosted', 28),
    ('1984-01-23 02:56:39', 'Skill watch arrive push challenge imagine.', 'Tour', 'Waiting', 4),
    ('1990-09-04 20:49:38', 'Stay factor relationship other public ahead.', 'Behavioral Interview', 'Ghosted', 14),
    ('2021-12-31 10:24:38', 'To seek mission indicate.', 'Technical Interview', 'Unknown', 2),
    ('2000-04-21 19:22:28', 'I spend effort himself actually create.', 'Behavioral Interview', 'Rejected', 5),
    ('1997-09-04 18:01:27', 'Common instead tend road.', 'Behavioral Interview', 'Rejected', 24),
    ('1987-01-05 05:25:32', 'Cold room defense fish.', 'Tour', 'Ghosted', 29),
    ('1997-07-07 02:47:42', 'Woman recent southern training mother moment.', 'Behavioral Interview', 'Ghosted', 13),
    ('2000-10-21 10:25:58', 'Respond somebody near read challenge.', 'Tour', 'Accepted', 16),
    ('2024-02-13 18:05:57', 'Program sometimes general dinner Mrs consider charge.', 'Tour', 'Ghosted', 17),
    ('1972-12-24 06:13:10', 'Reality within treat history.', 'Tour', 'Accepted', 22),
    ('1995-05-16 17:08:59', 'Artist civil cost again certain one physical.', 'Tour', 'Accepted', 23),
    ('1970-11-09 10:03:40', 'Worker season remain down.', 'Technical Interview', 'Unknown', 22),
    ('1972-10-19 11:58:29', 'Other important that face that herself write rich.', 'Technical Interview', 'Unknown', 6),
    ('2003-05-03 01:00:03', 'Beyond family man make.', 'Behavioral Interview', 'Accepted', 22),
    ('2018-05-01 17:00:11', 'Toward action have truth apply necessary hold.', 'Tour', 'Waiting', 10);

INSERT INTO data_reports (filter_criteria, description, creator_id) VALUES
    ('Research still computer account specific.', 'Stop ground hotel fight and.', 25),
    ('Gas degree either her deep.', 'Billion push minute Congress black.', 13),
    ('Pressure nice raise right something.', 'Look station glass reflect.', 26),
    ('Would money where become necessary explain smile.', 'Somebody indicate poor thought than.', 28),
    ('Fact nice than answer measure.', 'Owner not century mother great.', 24),
    ('Voice imagine method system sister service industry thought.', 'Available similar personal research impact green.', 26),
    ('Free energy cut whom analysis.', 'Section let campaign treatment family type.', 21),
    ('Whole trade campaign list often forget rate.', 'Writer lawyer institution shake course four.', 18),
    ('Face paper happen air where.', 'Coach drive spring take.', 28),
    ('Member bar including son free take product.', 'Situation country leave act fire rate.', 30),
    ('Growth answer already treatment forward.', 'Into six cut prove discuss.', 12),
    ('Class west every same.', 'Member appear scientist visit tree major.', 15),
    ('Require general car the movement.', 'Her look study old hand.', 18),
    ('Mean audience avoid security.', 'Million situation all memory fight exactly chair range.', 14),
    ('Sister follow law fast five.', 'Expert citizen idea modern worry human.', 27),
    ('North foreign artist wait.', 'Pattern leave summer two.', 8),
    ('Write note fast condition where.', 'Involve health ability interview.', 23),
    ('I ok court risk imagine firm.', 'Town well pick land lay.', 11),
    ('Challenge fly front.', 'Court through knowledge.', 25),
    ('Want relationship look stand nearly.', 'Chance quite knowledge site black.', 23),
    ('Hard toward behind expect that.', 'Economic billion test them serve any appear still.', 7),
    ('Season sound term particularly clear security serious.', 'Edge bit win.', 14),
    ('Meet example bar next interest car.', 'Nearly center wonder technology in.', 4),
    ('Follow effect maintain kind level them drop.', 'Wide agree year deep hope fast name similar.', 21),
    ('Owner call trade bank middle its unit.', 'Series arm laugh Mrs.', 17),
    ('Three bad size how present finally old.', 'Woman together maybe discussion positive write share.', 2),
    ('Kind administration glass special administration.', 'Gas political town make.', 5),
    ('Available thought marriage everyone process able message world.', 'Score sing read wife now police lot decide.', 14),
    ('Particular take view before.', 'Already story under firm.', 19),
    ('Every property score rest.', 'Address or store too.', 26);

INSERT INTO application_reports (report_id, application_id) VALUES
    (23, 14),
    (9, 23),
    (26, 4),
    (27, 1),
    (26, 7),
    (6, 17),
    (26, 21),
    (2, 3),
    (4, 30),
    (22, 1),
    (6, 2),
    (14, 8),
    (28, 1),
    (1, 4),
    (7, 26),
    (14, 16),
    (27, 7),
    (18, 30),
    (14, 12),
    (5, 5),
    (24, 6),
    (1, 30),
    (3, 2),
    (5, 22),
    (16, 22),
    (4, 25),
    (28, 6),
    (20, 26),
    (27, 12),
    (7, 13),
    (15, 6),
    (22, 30),
    (22, 19),
    (17, 20),
    (11, 3),
    (27, 24),
    (15, 5),
    (23, 5),
    (22, 27),
    (4, 13),
    (9, 18),
    (24, 27),
    (11, 8),
    (4, 8),
    (23, 21),
    (30, 26),
    (10, 24),
    (3, 5),
    (17, 21),
    (17, 7),
    (11, 24),
    (3, 18),
    (24, 20),
    (23, 9),
    (24, 22),
    (28, 2),
    (21, 6),
    (16, 25),
    (11, 21),
    (3, 14),
    (18, 20),
    (27, 21),
    (26, 30),
    (13, 4),
    (8, 30),
    (9, 27),
    (15, 24),
    (5, 3),
    (13, 9),
    (14, 21),
    (8, 24),
    (11, 12),
    (28, 28),
    (9, 15),
    (14, 20),
    (21, 12),
    (4, 26),
    (5, 8),
    (1, 13),
    (13, 6),
    (1, 19),
    (6, 21),
    (11, 29),
    (28, 25),
    (6, 10),
    (1, 26),
    (13, 5),
    (6, 28),
    (20, 12),
    (18, 12),
    (25, 11),
    (16, 2),
    (9, 8),
    (8, 5),
    (3, 8),
    (10, 29),
    (2, 9),
    (23, 11),
    (2, 5),
    (23, 4),
    (28, 24),
    (5, 13),
    (10, 1),
    (22, 10),
    (22, 15),
    (15, 30),
    (16, 18),
    (9, 6),
    (20, 19),
    (6, 20),
    (6, 26),
    (20, 13),
    (3, 29),
    (30, 15),
    (27, 10),
    (5, 30),
    (1, 12),
    (9, 30),
    (20, 3),
    (20, 21),
    (17, 24),
    (8, 21),
    (2, 2),
    (10, 20),
    (1, 15);
